### ISSUE TITLE
An error in PMUL3416

### ISSUE THREAD

**Issue by whatissimondoing** [tomyoung903/FusedChat#3]
There is an error in the total number of turns in "prepended.json"->PMUL3416. The correct data should be:
 "system: Booking was successful, the total fee is 140.8 GBP payable at the station .\n Reference number is : DK26RL4O. Can I help you with anything else?\n",  thus aligning with MultiWOZ2.4

**Comment by tomyoung903** [comment]
thanks for pointing that out! will be updated soon
Cheers,
Tom Young
PhD Student
School of Computer Science and Engineering (SCSE)
Nanyang Technological University (NTU)
50 Nanyang Ave, Singapore 639798

tomyoung903.github.io
