### ISSUE TITLE
 Solved:RuntimeError: Could not infer dtype of NoneType

### ISSUE THREAD

**Issue by steveluo01** [tomyoung903/FusedChat#4]
INFO:pytorch_transformers.modeling_utils:loading weights file .\gpt2\pytorch_model.bin
<restaurant-inform> <restaurant-recommend> <attraction-request> <hotel-request> <general-welcome> <train-offerbook> <booking-request> <restaurant-nooffer> <hospital-inform> <train-request> <train-nooffer> <general-bye> <hotel-select> <taxi-inform> <attraction-select> <attraction-nooffer> <booking-inform> <train-offerbooked> <general-greet> <train-inform> <train-select> <booking-nobook> <police-inform> <taxi-request> <attraction-inform> <restaurant-select> <hotel-recommend> <booking-book> <hospital-request> <general-reqmore> <restaurant-request> <hotel-nooffer> <hotel-inform> <attraction-recommend><leave> <people> <arrive> <pricerange> <arriveby> <ticket> <dest> <none> <leaveat> <car> <ref> <department> <open> <parking> <departure> <day> <type> <time> <stay> <internet> <phone> <choice> <destination> <name> <addr> <fee> <area> <post> <price> <depart> <id> <food> <stars>
67 332
INFO:D:\python\FusedChat-main\util.py:Load tokenized dataset from cache at ./data_cache/fused_cache
100%|██████████| 8439/8439 [00:08<00:00, 1032.53it/s]
100%|██████████| 999/999 [00:01<00:00, 948.01it/s]
100%|██████████| 1000/1000 [00:01<00:00, 938.89it/s]
Traceback (most recent call last):
  File "D:\python\FusedChat-main\train.py", line 409, in <module>
    train()
  File "D:\python\FusedChat-main\train.py", line 280, in train
    train_loader, val_loader, train_sampler, valid_sampler = get_data_loaders(args, tokenizer)
  File "D:\python\FusedChat-main\train.py", line 164, in get_data_loaders
    tensor = torch.tensor(dataset[input_name])
RuntimeError: Could not infer dtype of NoneType

**Comment by tomyoung903** [comment]
It seems like "dataset" might not have been loaded properly. Could you try to check "dataset" or "input_name"?

**Comment by steveluo01** [comment]
> It seems like "dataset" might not have been loaded properly. Could you try to check "dataset" or "input_name"?

sorry,I cannot understand how to check the "dataest" and "input_name".I didn't revise the code about "input_name".
But what I can confirm is,as you can see, the dataest should be 8439(train) 1000(valid) 1000(test) ,but the result is displayed as 
8439 999 1000 
100%|██████████| 8439/8439 [00:08<00:00, 1032.53it/s]
100%|██████████| 999/999 [00:01<00:00, 948.01it/s]
100%|██████████| 1000/1000 [00:01<00:00, 938.89it/s]

**Comment by steveluo01** [comment]
![image](https://user-images.githubusercontent.com/81147407/212443490-8ec526e4-6dc8-4ba4-a050-c5e2b091138a.png)

**Comment by tomyoung903** [comment]
Try printing out input_name and dataset

**Comment by tomyoung903** [comment]
Add print() before the line that gives the error

**Comment by steveluo01** [comment]
> Add print() before the line that gives the error

thank you for your reply. the output is"input_ids" when I add"print(input_name)" 
![image](https://user-images.githubusercontent.com/81147407/212444193-f543df1c-e35a-44f3-8c60-5b3ab6870989.png)

**Comment by tomyoung903** [comment]
Print dataset as well

**Comment by steveluo01** [comment]
when I add"print(dataest[input_name])"
![image](https://user-images.githubusercontent.com/81147407/212444302-45ba161c-d535-46d2-bb45-8275b9f6bb2e.png)
![image](https://user-images.githubusercontent.com/81147407/212444317-b4b3e0a5-aebf-4d40-b810-bad5600da343.png)

**Comment by steveluo01** [comment]
print(dataset)
![image](https://user-images.githubusercontent.com/81147407/212444426-263d63fe-1466-495c-b0d1-fa17193e19b3.png)

**Comment by tomyoung903** [comment]
how did you call train.py?

**Comment by steveluo01** [comment]
> 

by calling run_train_tod_single.py or run_train_fused.py,I get the same error

**Comment by steveluo01** [comment]
Is it possible that the version is a problem, I'm using python 3.9

**Comment by steveluo01** [comment]
Looking forward to your reply and could you show me your environment and version , etc

**Comment by tomyoung903** [comment]
Checking

**Comment by tomyoung903** [comment]
python version : 3.6.5 give this version a try

**Comment by tomyoung903** [comment]
did it work with 3.6.5?

**Comment by steveluo01** [comment]
Sorry,I haven't tried everything for the time being, because python 3.6 requires a lower version of CUDA, and then I need to lower the driver of my machine, but I am worried that not being able to succeed after the end will affect the original work. At the moment I'm wondering if the new version of Torch is updated when loading the dataset, and I'll try it out today.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tom ***@***.***&gt;; 
发送时间: 2023年1月16日(星期一) 凌晨2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tomyoung903/FusedChat] Hello,there is a question when I used the &quot;train.py&quot;    File &quot;D:\python\FusedChat-main\train.py&quot;, line 164, in get_data_loaders     tensor = torch.tensor(dataset[input_name]) RuntimeError: Could not infer dtype of NoneType (Issue #4)





 
did it work with 3.6.5?

**Comment by steveluo01** [comment]
Hello,Mr.Tom.
&nbsp; &nbsp; Firstly thank you for your help again.I am glad to tell you that I can run the"train.py" now,including run_train_fused.py and run_train_chitchat_single.py.In fact,I did't do anything,maybe modified some parameters. Though there are still some problems in&nbsp; run_train_tod_single.py, but it should be minor. I will try to solve it and I will send you an email if I cannot solve it.
&nbsp; &nbsp; Thank you again!
&nbsp; &nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tomyoung903/FusedChat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月16日(星期一) 凌晨2:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tomyoung903/FusedChat] Hello,there is a question when I used the "train.py"    File "D:\python\FusedChat-main\train.py", line 164, in get_data_loaders     tensor = torch.tensor(dataset[input_name]) RuntimeError: Could not infer dtype of NoneType (Issue #4)





 
did it work with 3.6.5?

**Comment by tomyoung903** [comment]
Glad to hear it!
